apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: alpine-runu
spec:
  selector:
    matchLabels:
      app: alpine-runu
  replicas: 1
  template:
    metadata:
      labels:
        app: alpine-runu
    spec:
      runtimeClassName: ukontainer
      containers:
      - name: alpine-runu
        image: alpine:latest
        imagePullPolicy: Always
        args: ["busybox", "ping", "-c", "50", "8.8.8.8"]
        env:
          - name: RUMP_VERBOSE
            value: "1"
